-- 코드를 입력하세요
WITH COMB AS (
    SELECT S.BOOK_ID, B.CATEGORY, B.AUTHOR_ID, A.AUTHOR_NAME, S.SALES_DATE, (B.PRICE * S.SALES) AS SALES
    FROM BOOK_SALES AS S
    JOIN BOOK AS B
    ON S.BOOK_ID = B.BOOK_ID
    JOIN AUTHOR AS A
    ON B.AUTHOR_ID = A.AUTHOR_ID
    WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
)

SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM COMB
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;