-- 코드를 작성해주세요
SELECT ID, IFNULL(SUB.CHILD_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA

LEFT JOIN (SELECT PARENT_ID, COUNT(ID) AS CHILD_COUNT
           FROM ECOLI_DATA
           GROUP BY PARENT_ID) AS SUB
ON ECOLI_DATA.ID = SUB.PARENT_ID