-- 코드를 입력하세요
SELECT YEAR(SALE.SALES_DATE) AS YEAR, MONTH(SALE.SALES_DATE) AS MONTH, USER.GENDER AS GENDER, 
    COUNT(DISTINCT SALE.USER_ID) AS USERS
FROM ONLINE_SALE AS SALE
INNER JOIN USER_INFO AS USER
ON SALE.USER_ID = USER.USER_ID
GROUP BY YEAR, MONTH, GENDER
HAVING GENDER IS NOT NULL
ORDER BY YEAR, MONTH, GENDER;