-- 코드를 입력하세요
WITH SUB AS (SELECT OUTS.ANIMAL_ID, OUTS.NAME, INS.DATETIME
             FROM ANIMAL_OUTS AS OUTS 
             LEFT JOIN ANIMAL_INS AS INS
             ON OUTS.ANIMAL_ID = INS.ANIMAL_ID)
SELECT ANIMAL_ID, NAME
FROM SUB
WHERE DATETIME IS NULL
ORDER BY ANIMAL_ID;