-- 코드를 입력하세요
WITH SUB AS (
    SELECT USER.USER_ID, ONLINE.SALES_DATE
    FROM USER_INFO AS USER
    LEFT JOIN ONLINE_SALE AS ONLINE
    ON USER.USER_ID = ONLINE.USER_ID

    WHERE YEAR(JOINED) = '2021'
)

SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT USER_ID) AS PURCHASED_USERS, ROUND(COUNT(DISTINCT USER_ID) / (SELECT COUNT(DISTINCT USER_ID) FROM SUB), 1) AS PUCHASED_RATIO
FROM SUB
WHERE SALES_DATE IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR, MONTH