WITH RECURSIVE SUB AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    SELECT E.ID, E.PARENT_ID, GENERATION + 1 AS GENERATION
    FROM SUB
    JOIN ECOLI_DATA AS E
    ON E.PARENT_ID = SUB.ID)
    
SELECT COUNT(ID) AS COUNT, GENERATION
FROM SUB
WHERE ID NOT IN (SELECT DISTINCT PARENT_ID
                 FROM ECOLI_DATA
                 WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION
ORDER BY GENERATION;