-- 코드를 입력하세요
WITH SUB AS (
    SELECT H.FLAVOR, (H.TOTAL_ORDER + SUB.TOTAL_ORDER) AS TOTAL_ORDER
    FROM FIRST_HALF AS H 
    LEFT JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
               FROM JULY
               GROUP BY FLAVOR) AS SUB
    ON H.FLAVOR = SUB.FLAVOR

    UNION

    SELECT H.FLAVOR, (H.TOTAL_ORDER + SUB.TOTAL_ORDER) AS TOTAL_ORDER
    FROM FIRST_HALF AS H 
    RIGHT JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
                FROM JULY
                GROUP BY FLAVOR) AS SUB
    ON H.FLAVOR = SUB.FLAVOR

    ORDER BY TOTAL_ORDER DESC
    LIMIT 3
    )
SELECT FLAVOR FROM SUB; 