-- 코드를 입력하세요
SELECT B.HOUR, COUNT(A.ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS AS A

RIGHT JOIN (SELECT ROW_NUMBER() OVER(ORDER BY ANIMAL_ID ASC)-1 AS HOUR
            FROM ANIMAL_OUTS
            LIMIT 24) AS B
ON HOUR(A.DATETIME) = B.HOUR

GROUP BY B.HOUR
ORDER BY B.HOUR;