-- 코드를 작성해주세요
WITH SUB AS (
    SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME,  
        (CASE
         WHEN S.CATEGORY = 'Front End' THEN 1
         ELSE 0
        END) AS FRONT
    FROM DEVELOPERS AS D
    RIGHT JOIN SKILLCODES AS S
    ON D.SKILL_CODE & S.CODE)
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM SUB
GROUP BY ID, EMAIL, FIRST_NAME, LAST_NAME
HAVING SUM(FRONT) > 0
ORDER BY ID;