-- 코드를 입력하세요
SELECT USER.USER_ID, USER.NICKNAME, SUM(BOARD.PRICE) AS TOTAL_SALES
FROM USED_GOODS_USER AS USER
RIGHT JOIN USED_GOODS_BOARD AS BOARD
ON USER.USER_ID = BOARD.WRITER_ID
WHERE BOARD.STATUS = 'DONE'
GROUP BY USER.USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES;