-- 코드를 입력하세요
WITH SUB AS (SELECT INS.ANIMAL_ID, INS.NAME, INS.DATETIME AS START, OUTS.DATETIME AS FINISH
             FROM ANIMAL_INS AS INS
             LEFT JOIN ANIMAL_OUTS AS OUTS
             ON INS.ANIMAL_ID = OUTS.ANIMAL_ID)
SELECT ANIMAL_ID, NAME
FROM SUB
WHERE START > FINISH
ORDER BY START;