-- 코드를 작성해주세요
SELECT DEP.DEPT_ID, DEP.DEPT_NAME_EN, ROUND(AVG(EMP.SAL), 0) AS AVG_SAL
FROM HR_DEPARTMENT AS DEP
RIGHT JOIN HR_EMPLOYEES AS EMP
ON DEP.DEPT_ID = EMP.DEPT_ID
GROUP BY EMP.DEPT_ID
ORDER BY AVG_SAL DESC;
