-- 코드를 입력하세요
SELECT A.CATEGORY, SUM(B.SALES) AS TOTAL_SALES
FROM BOOK AS A
JOIN (SELECT BOOK_ID, SALES
      FROM BOOK_SALES
      WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31') AS B
ON A.BOOK_ID = B.BOOK_ID
GROUP BY CATEGORY
ORDER BY CATEGORY;